services:
  - type: web
    name: tranferhub
    env: node
    plan: free
    buildCommand: npm run install-all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tranferhub-db
          property: connectionString
    
  - type: pserv
    name: tranferhub-db
    env: postgres
    plan: free
    databaseName: sendanywhere_clone
    databaseUser: postgres
